-- ==============================================================================
-- MIGRATION: CONFIGURAÇÃO DE OBJETIVOS E ATIVIDADES (COM PERSISTÊNCIA E RLS)
-- ==============================================================================
-- Este script cria as tabelas necessárias para persistir a estrutura de Objetivos
-- e Atividades.
--
-- VERSÃO LIMPA: SEM DADOS DE MOCK INICIAIS.
--
-- INSTRUÇÕES DE USO:
-- 1. Copie e cole este conteúdo no Editor SQL do Supabase.
-- 2. Execute o script.
-- 3. Verifique se as tabelas 'objectives' e 'activities' foram criadas.
-- ==============================================================================

-- 1. Tabela de Objetivos (Objectives)
CREATE TABLE IF NOT EXISTS public.objectives (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Permite IDs manuais ou autogerados
    title text NOT NULL,
    status text DEFAULT 'on-track', -- 'on-track', 'delayed', etc.
    created_at timestamptz DEFAULT now()
);

-- 2. Tabela de Atividades (Activities)
-- Nota: O ID é text para manter compatibilidade com o formato "1.1", "1.2".
CREATE TABLE IF NOT EXISTS public.activities (
    id text PRIMARY KEY, 
    objective_id bigint REFERENCES public.objectives(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    created_at timestamptz DEFAULT now()
);

-- 3. Habilitar Segurança por Linha (RLS)
ALTER TABLE public.objectives ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;

-- 4. Definir Políticas de Acesso (RLS Policies)

-- LEITURA: Permitido para todos os usuários autenticados
DROP POLICY IF EXISTS "Permitir leitura para usuários autenticados (Objectives)" ON public.objectives;
CREATE POLICY "Permitir leitura para usuários autenticados (Objectives)"
ON public.objectives FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "Permitir leitura para usuários autenticados (Activities)" ON public.activities;
CREATE POLICY "Permitir leitura para usuários autenticados (Activities)"
ON public.activities FOR SELECT
TO authenticated
USING (true);

-- ESCRITA (Insert, Update, Delete): Apenas Admins e Superadmins
-- Verifica a role na tabela profiles
DROP POLICY IF EXISTS "Permitir escrita para Admins (Objectives)" ON public.objectives;
CREATE POLICY "Permitir escrita para Admins (Objectives)"
ON public.objectives FOR ALL
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid()
        AND profiles.role IN ('admin', 'superadmin')
    )
);

DROP POLICY IF EXISTS "Permitir escrita para Admins (Activities)" ON public.activities;
CREATE POLICY "Permitir escrita para Admins (Activities)"
ON public.activities FOR ALL
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid()
        AND profiles.role IN ('admin', 'superadmin')
    )
);

-- FIM DA MIGRAÇÃO
